-- 코드를 작성해주세요
SELECT SUM(G.SCORE) as SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
GROUP BY 
    E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
HAVING 
    SUM(G.SCORE) IS NOT NULL
ORDER BY SUM(G.SCORE) DESC
LIMIT 1
